repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff check --fix
        language: system
        types_or: [python, pyi]
        require_serial: true
        files: ^(sqlframe/|tests/)
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format
        language: system
        types_or: [python, pyi]
        require_serial: true
        files: ^(sqlframe/|tests/)
      - id: ty
        name: ty
        entry: ty check sqlframe tests
        language: system
        types: [ python ]
        files: ^(sqlframe/|tests/)
        pass_filenames: false
