name: SQLFrame
on:
  push:
    branches:
    - main
    paths:
      - 'sqlframe/**'
      - 'tests/**'
      - 'Makefile'
      - 'setup.py'
  pull_request:
    types:
    - synchronize
    - opened
    paths:
    - 'sqlframe/**'
    - 'tests/**'
    - 'Makefile'
    - 'setup.py'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      PYTEST_XDIST_AUTO_NUM_WORKERS: 4
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: make install-dev
    - name: Run Style
      run: make style
    - name: Setup Postgres
      uses: ikalnytskyi/action-setup-postgres@v7
    - name: Setup GizmoSQL
      env:
        INIT_SQL_COMMANDS: "CALL dsdgen(sf=0.01);"
      run: |
        pushd /tmp
        curl --location -o gizmosql.zip https://github.com/gizmodata/gizmosql/releases/latest/download/gizmosql_cli_linux_amd64.zip
        unzip gizmosql.zip
        ./gizmosql_server --password gizmosql_password --print-queries &
        sleep 10
        popd
    - name: Run tests
      run: make local-test
